name: Build and Test

on:
  workflow_dispatch:
    inputs:
      GenerateTestData:
        type: choice
        description: Generate new TestData or use Existing TestData
        options: 
          - true
          - false
      ModelType:
        type: choice
        description: Choose which model to use
        options: 
          - openai
          - bedrock
  push:
    paths:
      - 'input/*'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Set up environment variables
        run: |
          echo "OPENAI_API_KEY=sk-proj-h4KoEgliaM2W6wMIKPSlT3BlbkFJBtF36iwV9jw8HPzFxMuv" >> $GITHUB_ENV
          echo "AWS_REGION=us-east-1" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY_ID=AKIA6ODU53PAS7WAKN74" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=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" >> $GITHUB_ENV
      - name: Print Node Version
        run: node --version
      - name: Install Packages
        run: npm install --legacy-peer-deps
      - name: Run Index.js file - User Input
        if: ${{ github.event.inputs.GenerateTestData != '' && github.event.inputs.ModelType != '' }}
        run: |
          echo generateTestData value is empty
          node index.js generateTestData=${{inputs.GenerateTestData}} modelType=${{inputs.ModelType}}
      - name: Run Index.js file - Github variable Input
        if: ${{ github.event.inputs.GenerateTestData == '' && github.event.inputs.ModelType == '' }}
        run: |
          echo generateTestData value is empty
          node index.js generateTestData=${{vars.GenerateTestData}} modelType=${{vars.ModelType}}
      - name: Install Packages
        run: npx codeceptjs run --reporter mochawesome
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-automation-artifact
          path: output/*
        